### ISSUE TITLE
Error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JeanPluzo** [KeepSec-Technologies/Mail2Go#1] opened 2024-01-09 14:38 UTC
Hi,

I like this project's idea!
Sadly I tried to send a single e-mail but got following error:
 `Error sending email: dial failed: EOFpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5e8ed8]`

`goroutine 1 [running]:`
`github.com/wneessen/go-mail/smtp.(*Client).hello(0xc0000b1b50?)`
`        /home/jordancup/go/pkg/mod/github.com/wneessen/go-mail@v0.4.0/smtp/smtp.go:110 +0x18`
`github.com/wneessen/go-mail/smtp.(*Client).Noop(0x4ba71c?)`
`        /home/jordancup/go/pkg/mod/github.com/wneessen/go-mail@v0.4.0/smtp/smtp.go:432 +0x1e`
`github.com/wneessen/go-mail.(*Client).checkConn(0xc0000ca100)`
`        /home/jordancup/go/pkg/mod/github.com/wneessen/go-mail@v0.4.0/client.go:593 +0x45`
`github.com/wneessen/go-mail.(*Client).Close(0xc0000ca100)`
`        /home/jordancup/go/pkg/mod/github.com/wneessen/go-mail@v0.4.0/client.go:541 +0x25`
`main.sendEmail({0x7ffdb3ead4bb, 0x14}, 0x1d1, {0x7ffdb3ead4da, 0xa}, {0x7ffdb3ead4e8, 0xd}, {0x7ffdb3ead4f9, 0x15}, {0xc00008a960, ...}, ...)`
`        /mnt/c/Users/jcup45/OneDrive/Documents/Code Snippets/Go/Mail2Go/smtp.go:48 +0x517`
`main.main()`
`        /mnt/c/Users/jcup45/OneDrive/Documents/Code Snippets/Go/Mail2Go/main.go:184 +0x92f`

FWIW I'm behind a proxy.
OS is Ubuntu 20.04.
I followed the installation instructions. I did not try to build it myself.
If you need more info I'll be happy to provide it.

Regards,
J.

**Comment by JCoupalK** [comment] 2024-02-06 03:32
Sorry for the late response I didn't saw the issue.

Your SMTP server is behind a proxy correct? 

Does all the connection informations has been confirmed to work in another client? (eg: Thunderbird or anything).

Because the error "Error sending email: dial failed: EOFpanic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5e8ed8]" means that the something to make the server connection has failed. Might be the port so you could try other ports maybe.

Hope it helped!

**Comment by JCoupalK** [comment] 2024-02-06 05:44
Hi, sorry for the late response I didn't see this issue.

I've been able to reproduce your issue and it seems I did something wrong with how I handled the TLS ports.

Good news is it should now be fixed in the latest release (1.1.3): 
[https://github.com/KeepSec-Technologies/Mail2Go/releases/tag/1.1.3](https://github.com/KeepSec-Technologies/Mail2Go/releases/tag/1.1.3)

If the issue still persists or you weren't using a TLS port like 465 please tell me.

Thank you.

**Closed as completed by JCoupalK** 2024-02-06 05:44 UTC
